// import '../styles/output.scss';
var Ship = require('./ship');
var Gameboard = require('./gameboard');
var gb = new Gameboard();
gb.createUI();
var ship = new Ship(4);
gb.placeShipVertical(ship, 2, 3);
var ship2 = new Ship(4);
gb.placeShipHorizontal(ship2, 0, 2);
gb.recieveAttack(0, 0);
gb.recieveAttack(0, 2);
gb.recieveAttack(0, 3);
gb.recieveAttack(0, 4);
gb.recieveAttack(0, 5);
// const ship2 = new Ship(3);
// gb.placeShipVertical(ship2, 3, 1);
console.log(gb);
gb.report();
console.log('Hello, World!');
